networks:
  dev:

services:
  app:
      build: 
        context: .
        dockerfile: Dockerfile
      command:  >
        bash -c "
          while ! nc -z db 5432; do
            echo 'Waiting for database...';
            sleep 5;
          done;
          alembic upgrade head;
          python3 bot/main.py
        "
      volumes:
        - ./bot:/app/bot
      ports:
        - "8000:8000"
      depends_on:
        - db
      restart: always
      env_file:
        - .env    
      networks:
        - dev
                
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
        - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shamantest
    ports:
      - "5433:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
        - dev

volumes:
  postgres_data: